config/routes.rb
Rails.application.routes.draw do
  root "parks#index"
  resources :parks, only: [:index, :new, :create,:show] do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/park.rb
class Park < ApplicationRecord
  validates :number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  def index
    @park = Park.first
  end

  def new
    @park = Park.new
  end

  def create
    @park = Park.create(park_params)
    if @park.save
      if @park.id != 1
      @pronumber = Park.first
      @pronumber.delete
      render :index
      else
      render :index
      end
    else
      redirect
    end
  end

  def show
    @park = Park.first
    end_point
    tictok
  end

  private
  def park_params
    params.require(:park).permit(:number)
  end

  def tictok
    start_point
    @@fee = @@end_point - @point 
    if @@fee <= 1800
        @finalfee = 0
    elsif @@fee < 21600
        @finalfee = 100
    else
      final_cul
      @finalfee = @@final_fee
    end

  end

  def start_point
    @point = @park.created_at.tv_sec
  end

  def end_point
    t = Time.now
    @@end_point = t.tv_sec
  end

  def final_cul
    ex_time = @@fee - 21600
    ex = ex_time / 21600
    exb = ex.floor
    @@final_fee = 100 + exb * 50
  end

  def redirect
    redirect_to  root_path,notice:'redirectに成功しました'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CoinParkingApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/parks/index.html.haml
.wrapper
  .header
    .title
      = link_to parks_path (@park), class: "indexLink"  do
        ParkApp
  .contents
    .content
      .park
        .sign
          駐輪番号
        .park__number
          = @park.number
      .check
        = link_to  park_path (@park) do
          料金を確認する 
      .new-button
        = link_to new_park_path do
          駐輪し直す   

app/views/parks/new.html.haml
.wrapper
  .header
    .title
      = link_to parks_path (@park), class: "indexLink"  do
        ParkApp
  .contents
    = form_for @park, local: true  do |f|
      .mention
        .ask
          駐輪番号を入力して下さい
      .number
        = f.number_field :number
      .send_button
        = f.submit "保存する"

app/views/parks/show.html.haml
.wrapper
  .header
    .title
      = link_to parks_path (@park), class: "indexLink"  do
        ParkApp
  .contents
    .content
      .park
        .sign
          駐輪番号
        .park__number
          = @park.number 
      .price
        %span
          ¥
        = @finalfee
        %span
          円
      .buttons
        .buttons__new
          = link_to new_park_path do
            新しく駐輪番号を登録する
        .buttons__back
          = link_to  parks_path do
            戻る